config/routes.rb
BidWeibo::Application.routes.draw do

  

  resources :mb_replies do 
    member do 
      get :conversation
      get :talk
    end
  end
  resources :mb_posts, :path => "post" do
    collection do
      get :get_reply
      post :forward
    end
    member do
      get :repost
    end
  end
  resources :users, :path => "" do
    member do
      get :attention
      get :myfans
      get :myfollow
      get :fans
      get :follow
    end
  end
  resources :friendships
end

app/views/shared/_day_topic.html.erb
<div class="right pull-left">
	<div class="widget">
		<h2>今日话题</h2>
		<ul>
		    <li><a href="">楼继伟：按揭贷款将纳入个税抵扣</a></li>
			<li><a href="">券商投资逻辑：ROE如何提升</a></li>
			<li><a href="">苏宁频换新装，急需基因重组</a></li>
			<li><a href="">二级市场姐，在天涯</a></li>
			<li><a href="">医药反腐日烈，远离潜规则依赖股！</a></li>
		</ul>
	</div>
</div>

app/views/shared/_friendship.html.erb
<div id="relation_<%= user.id %>">
	<% if current_user.follower_of?(user) && current_user.followee_of?(user) %>
		相互关注 <%= link_to '取消', friendship_path(user), :remote => true, :method => :delete, data: { confirm: '确认要取消关注?' } %>
	<% elsif current_user.follower_of?(user) %>
		已关注 <%= link_to '取消', friendship_path(user), :remote => true, :method => :delete, data: { confirm: '确认要取消关注?' } %>
	<% else %>
		<%= link_to '关注', friendships_path(:uid => user.id), :remote => true, :method => :post %>
	<% end %>
</div>

app/views/shared/_new_post.html.erb
<div class="post">
	<%= form_for MbPost.new, :remote => true, :role => "form" do |f| %>
  			<%= f.text_area :content, :class => "form-control", :row => "4" %>
  			<%= f.submit '保存', :class => "btn btn-success pull-right btn-post" %>
	<% end %>
</div>
<script type="text/javascript">
	$("#mb_post_content").atwho({
  		at: "@",
  		limit: 20,
  		data: "/users/attention.json"
	});
</script>

app/views/shared/_user_info.html.erb
<div class="left pull-left">
			<div class="avatar">
				<%= image_tag user.photo.url() %>
				<p><%= link_to user.nick_name, user %></p>
				<p><%= link_to '个人资料', edit_user_path(user) if user == current_user %></p>
				<p>
					<%= render "shared/friendship", :user => user if user != current_user %>
				</p>
			</div>
			<ul>
				<% if user == current_user %>
					<li><%= link_to "粉丝（#{user.followers_count}）", myfans_user_path(user) %></li>
					<li><%= link_to "关注（#{user.followees_count}）", myfollow_user_path(user) %></li>
					<li><a href="">评论我的</a></li>
					<li><a href="">提到我的</a> <span class="label label-danger">3</span></li>
					<li><a href="">私信</a></li>
				<% else %>
					<li><%= link_to "他的粉丝（#{user.followers_count}）", fans_user_path(user) %></li>
					<li><%= link_to "他的关注（#{user.followees_count}）", follow_user_path(user) %></li>
				<% end %>
			</ul>
		</div>