config/routes.rb
BidWeibo::Application.routes.draw do

  

  resources :mb_replies do 
    member do 
      get :conversation
      get :talk
    end
  end
  resources :mb_posts, :path => "post" do
    collection do
      get :get_reply
      post :forward
    end
    member do
      get :repost
    end
  end
  resources :users, :path => "" do
    member do
      get :attention
      get :myfans
      get :myfollow
      get :fans
      get :follow
    end
  end
  resources :friendships
end

app/models/mb_post.rb
class MbPost
	include Mongoid::Document
	include Mongoid::Timestamps
	field :title
	field :content
	field :mb_replies_count, :type => Integer, :default => 0
	field :forwards_count, :type => Integer, :default => 0
	field :path_ids, :type => Array, :default => []
	has_many :mb_pictures
	has_many :mb_replies, :dependent => :destroy
	belongs_to :user, :inverse_of => :mb_posts, :counter_cache => true
	index({ mb_replies_count: 1 })

	default_scope desc(:id)

	before_create :set_mentions
	after_create :update_homeline, :set_path_ids

	def update_homeline
		self.user.userline.push(mb_post_ids: self.id)
		Homeline.where(:user_id.in => self.user.follower_ids_include_self).push(mb_post_ids: self.id)
	end

	def set_mentions
		self.content = self.content.gsub(/@([\p{Han}\p{Alnum}\-_]{3,24})/){|a| "<a href='/#{User.find_by(:nick_name => $1).try(:id)}'>@#{$1}</a>"}
		#self.content.scan(/@[\p{Han}\p{Alnum}\-_]{3,24}/).each do |name|
		#end
	end

	def set_path_ids
		MbPost.where(:id.in => self.path_ids).inc(forwards_count: 1)
		self.set(path_ids: self.path_ids.push(self.id).flatten)
	end

	def has_many_path?
		self.path_ids.size > 1
	end

end

app/controllers/mb_posts_controller.rb
class MbPostsController < ApplicationController

	def create
		@mb_post = MbPost.new(params.require(:mb_post).permit(:content))
		@mb_post.user_id = current_user.id
		if @mb_post.save
			respond_to  do |format|
      			format.html
      			format.js
    		end
		else
			redirect_to users_path
		end
	end

	def repost
		@mb_post = MbPost.find(params[:id])
		@origin_mb_post = MbPost.find(@mb_post.path_ids.first)
		@value = @mb_post.has_many_path? ? "//@#{@mb_post.user.nick_name}:#{@mb_post.content}" : ""
	end

	def forward
		@parent_mb_post = MbPost.find(params[:mid])
		@mb_post = MbPost.new(params.require(:mb_post).permit(:content))
		@mb_post.path_ids = @parent_mb_post.path_ids
		@mb_post.user_id = current_user.id
		if @mb_post.save
			respond_to  do |format|
      			format.html{redirect_to users_path}
      			format.js
    		end
		else
			redirect_to users_path
		end
	end

	def destroy
		@mb_post = MbPost.find(params[:id])
		raise "只能删除自己的文章！" if @mb_post.try(:user) != current_user
		if @mb_post.destroy
			respond_to  do |format|
      			format.html
      			format.js
    		end
    	else
    		redirect_to users_path
		end
	end

	def get_reply
    @user = User.find params[:puid]
    @mb_post = MbPost.find params[:pid]
    @mb_replies = @mb_post.mb_replies
    @mb_reply = MbReply.new
    respond_to do |format|
        format.html { render :partial => "replies" }
    end
  end

end

app/views/mb_posts/_mb_post.html.erb
<li class="clearfix">
	<div class="avatar pull-left">
		<%= image_tag mb_post.user.photo.url(:thumb) %>
	</div>
	<div class="content">
		<p class="author">
			<%= link_to mb_post.user.nick_name, mb_post.user %>
		</p>
		<h4><%= link_to mb_post.title, mb_post if mb_post.title %></h4>
		<div class="summary">
			<%= mb_post.content %>
		</div>
		<div class="meta">
			<div class="info pull-left"><a href="">今天 12:30</a></div>
				<div class="actions pull-right">
					<a href="">转发(<%= mb_post.forwards_count %>)</a>|<a href="">分享</a>|<a href="">收藏</a>|<a href="">评论(<%= mb_post.replies_count %>)</a>
				</div>
			</div>
		</div>
	</li>

app/views/mb_posts/_origin_mb_post.html.erb
	<div class="content">
		<p class="author">
			<%= link_to mb_post.user.nick_name, mb_post.user %>
		</p>
		<h4><%= link_to mb_post.title, mb_post if mb_post.title %></h4>
		<div class="summary">
			<%= mb_post.content %>
		</div>
		<div class="meta">
			<div class="info pull-left"><%= mb_time(mb_post.try(:created_at)) %></div>
			<div class="actions pull-right">
				<%= link_to "删除", mb_post_path(mb_post), :method => :delete, :remote => true, data: { confirm: '确认要删除?' }, :class => "delete" if mb_post.user == current_user %>
				<%= link_to "转发(#{mb_post.forwards_count})", repost_mb_post_path(mb_post), :remote => true %>
				|<a href="">分享</a>|<a href="">收藏</a>|<%= link_to "评论(#{mb_post.mb_replies_count})", "javascript:void(0);", :action_data => "puid=#{mb_post.user.id}&uid=#{current_user.id}&pid=#{mb_post.id}", :class => "homepage_reply_link" %>
			</div>
		</div>
	</div>

app/views/mb_posts/_replies.html.erb
<div class="post" style="margin-top:40px;">
	<%= form_for @mb_reply, :remote => true, :role => "form" do |f| %>
  			<%= f.text_area :content, :class => "form-control", :row => "4" %>
  			<%= f.hidden_field :mb_post_id, :value => @mb_post.id %>
  			<%= f.submit '保存', :class => "btn btn-success pull-right btn-post" %>
	<% end %>
</div>
<div class="comments">
	<h4>全部评论（<%= @mb_post.mb_replies_count %>）</h4>
	<ul class="comment-list">
		<% @mb_replies.each do |mb_reply| %>
			<%= render "mb_replies/mb_reply", :mb_reply => mb_reply %>
		<% end %>
	</ul>
</div>

app/views/mb_posts/_repost.html.erb
	<div class="content">
		<p class="author">
			<%= link_to "@#{@origin_mb_post.user.nick_name}", @origin_mb_post.user %>:<%= @origin_mb_post.content %>
		</p>
	</div>
	<div class="post">
		<%= form_for(MbPost.new, :url => "/post/forward", :role => "form") do |f| %>
  			<%= f.text_area :content, :class => "form-control", :row => "4", :value => raw(@value) %>
  			<%= hidden_field_tag :mid, @mb_post.id %>
  			<%= f.submit '保存', :class => "btn btn-success pull-right btn-post" %>
		<% end %>
	</div>
<script type="text/javascript">
$("#mb_post_content").focus();
</script>

app/views/mb_posts/create.js.erb
<% if @mb_post.errors.blank? %>
  $(".status-list").prepend("<%= escape_javascript(render(:partial => 'mb_post', :locals => { :mb_post => @mb_post})) %>");
  $("#mb_post_content").val("");
<% else %>
  alert("<%= @mb_post.errors.full_messages %>");
<% end %>

app/views/mb_posts/destroy.js.erb
$("#<%= @mb_post.id %>").remove();

app/views/mb_posts/repost.js.erb
$("#repost_dialog").html("<%= escape_javascript(render 'repost') %>");
$("#repost_dialog").dialog({height: 450,width:500 });