config/routes.rb
BidWeibo::Application.routes.draw do

  

  resources :mb_replies do 
    member do 
      get :conversation
      get :talk
    end
  end
  resources :mb_posts, :path => "post" do
    collection do
      get :get_reply
      post :forward
    end
    member do
      get :repost
    end
  end
  resources :users, :path => "" do
    member do
      get :attention
      get :myfans
      get :myfollow
      get :fans
      get :follow
    end
  end
  resources :friendships
end

app/models/mb_reply.rb
class MbReply
	include Mongoid::Document
	include Mongoid::Timestamps
	field :content
	field :talk_ids, :type => Array, :default => []
	belongs_to :user, :inverse_of => :mb_replies
	belongs_to :mb_post, :counter_cache => true
	default_scope desc(:id)
	after_create :set_talk_id

	def set_talk_id
		self.set(talk_ids: self.talk_ids.push(self.id).flatten)
	end

	def can_read_conversation?
		self.talk_ids.length > 1
	end
end

app/controllers/mb_replies_controller.rb
class MbRepliesController < ApplicationController
	def create
		@mb_reply = MbReply.new(params.require(:mb_reply).permit(:content, :mb_post_id))
		unless params[:old_mb_reply].blank?
			@old_mb_reply = MbReply.find(params[:old_mb_reply]) 
			@mb_reply.talk_ids = @old_mb_reply.talk_ids
		end
		@mb_reply.user_id = current_user.id
		if @mb_reply.save
			respond_to  do |format|
      			format.html
      			format.js
    		end
		else
			redirect_to users_path
		end
	end

	def talk
		@old_mb_reply = MbReply.find(params[:id])
		@mb_post = @old_mb_reply.mb_post
		@user = @old_mb_reply.user
		@mb_reply = MbReply.new
		respond_to  do |format|
      		format.html
      		format.js
    	end
	end

	def conversation
		@mb_reply = MbReply.find params[:id]
		@mb_replies = MbReply.where(:id.in => @mb_reply.talk_ids)
	end
end

app/views/mb_replies/_conversation.html.erb
<% @mb_replies.each do |mb_reply| %>
  <li class="clearfix" id="<%= mb_reply.id %>">
	<div class="avatar pull-left">
		<%= image_tag mb_reply.user.photo.url(:thumb) %>
	</div>
	<div class="content">
		<p class="author">
			<%= link_to mb_reply.user.try(:nick_name), mb_reply.user %>
		</p>
		<div class="summary">
			<%= mb_reply.content %>
		</div>
		<div class="meta">
			<div class="info pull-left"><%= mb_time(mb_reply.try(:created_at)) %></div>
			<div class="actions pull-right">
				<%= link_to "回复", talk_mb_reply_path(mb_reply), :remote => true %>
			</div>
		</div>
	</li>
<% end %>

app/views/mb_replies/_mb_reply.html.erb
<li class="clearfix" id="<%= mb_reply.id %>">
	<div class="avatar pull-left">
		<%= image_tag mb_reply.user.photo.url(:thumb) %>
	</div>
	<div class="content">
		<p class="author">
			<%= link_to mb_reply.user.try(:nick_name), mb_reply.user %>
		</p>
		<div class="summary">
			<%= mb_reply.content %>
		</div>
		<div class="meta">
			<div class="info pull-left"><%= mb_time(mb_reply.try(:created_at)) %></div>
			<div class="actions pull-right">
				<%= link_to "查看对话", conversation_mb_reply_path(mb_reply), :remote => true if mb_reply.can_read_conversation? %><a href="">赞</a>|<%= link_to "回复", talk_mb_reply_path(mb_reply), :remote => true %>
			</div>
		</div>
</li>

app/views/mb_replies/_new_reply.html.erb
<div class="post" style="margin-top:40px;" id="conversation_<%= @old_mb_reply.id %>">
	<%= form_for @mb_reply, :remote => true, :role => "form" do |f| %>
  			<%= f.text_area :content, :class => "form-control", :row => "4", :value => "回复@#{@user.nick_name}:" %>
  			<%= f.hidden_field :mb_post_id, :value => @mb_post.id %>
  			<%= hidden_field_tag "old_mb_reply", @old_mb_reply.id  %>
  			<%= f.submit '保存', :class => "btn btn-success pull-right btn-post" %>
	<% end %>
</div>

app/views/mb_replies/conversation.js.erb
$("#conversation_dialog").html("<%= escape_javascript(render 'conversation', :mb_replies => @mb_replies) %>");
$("#conversation_dialog").dialog({height: 450,width:500 });

app/views/mb_replies/create.js.erb
<% if @mb_reply.errors.blank? %>
  $(".comment-list").prepend("<%= escape_javascript(render(:partial => 'mb_reply', :locals => { :mb_reply => @mb_reply})) %>");
  $("#mb_reply_content").val("");
  $("#conversation_<%= @old_mb_reply.try(:id) %>").remove();
<% else %>
  alert("<%= @mb_reply.errors.full_messages %>");
<% end %>

app/views/mb_replies/talk.js.erb
$("#<%= @old_mb_reply.id %>").append("<%= escape_javascript(render(:partial => 'new_reply')) %>");